name: Publish documentation website to GitHub Pages
on:
  workflow_dispatch: {}
  push:
    branches: ["main"]

jobs:
  publish:
    name: Publish documentation website

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 9.0.x

        - uses: retypeapp/action-build@latest
          id: retype-build

        - id: repo_meta
          name: Get repository description
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            desc=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/${GITHUB_REPOSITORY}" | jq -r '.description // ""')
            echo "description=$desc" >> $GITHUB_OUTPUT;

        - uses: alexasselin008/retypeapp-action-build-llms@main
          with:
            verbose: true
            description: ${{ steps.repo_meta.outputs.description }}
            output: ${{ steps.retype-build.outputs.retype-output-path}}

        - uses: retypeapp/action-github-pages@latest
          with:
            update-branch: true
